/**:
  ros__parameters:
    plugin_denylist:
      - '*'
      # # common

      # # extras
      # - image_pub
      # - vibration
      # - distance_sensor
      # - rangefinder
      # - wheel_odometry

    plugin_allowlist:
      - 'sys_*'
      - imu
      - onboard_computer_status
      - distance_sensor
      - local_position
      - command
      - companion_process_status
      - vision_pose
      - setpoint_position
      - setpoint_velocity
